name: GitHub Copilot CLI Action

on:
  workflow_call:
    inputs:
      prompt:
        description: 'The prompt to execute with Copilot CLI'
        required: true
        type: string
      
      system_prompt:
        description: 'System prompt with guidelines that should be emphasized and followed'
        required: false
        type: string
        default: ''
      
      mcp_config:
        description: 'MCP server configuration as JSON string or file path (prefix with @)'
        required: false
        type: string
        default: ''
      
      copilot_model:
        description: 'AI model to use (gpt-5, claude-sonnet-4, claude-sonnet-4.5)'
        required: false
        type: string
        default: 'claude-sonnet-4.5'
      
      allow_all_tools:
        description: 'Allow all tools to run automatically without confirmation'
        required: false
        type: boolean
        default: true
      
      allow_all_paths:
        description: 'Disable file path verification and allow access to any path'
        required: false
        type: boolean
        default: false
      
      additional_directories:
        description: 'Comma-separated list of additional directories to allow file access'
        required: false
        type: string
        default: ''
      
      allowed_tools:
        description: 'Comma-separated list of allowed tools (if not using allow_all_tools)'
        required: false
        type: string
        default: ''
      
      denied_tools:
        description: 'Comma-separated list of denied tools'
        required: false
        type: string
        default: ''
      
      disable_builtin_mcps:
        description: 'Disable all built-in MCP servers'
        required: false
        type: boolean
        default: false
      
      disable_mcp_servers:
        description: 'Comma-separated list of MCP servers to disable'
        required: false
        type: string
        default: ''
      
      enable_all_github_mcp_tools:
        description: 'Enable all GitHub MCP server tools instead of default CLI subset'
        required: false
        type: boolean
        default: false
      
      log_level:
        description: 'Log level (none, error, warning, info, debug, all, default)'
        required: false
        type: string
        default: 'info'
      
      working_directory:
        description: 'Working directory to run the CLI from'
        required: false
        type: string
        default: '.'
      
      node_version:
        description: 'Node.js version to use'
        required: false
        type: string
        default: '22'
      
      timeout_minutes:
        description: 'Timeout for the Copilot CLI execution in minutes'
        required: false
        type: number
        default: 30
    
    secrets:
      GITHUB_TOKEN:
        description: 'GitHub token for authentication'
        required: false
      
      MCP_ENV_VARS:
        description: 'JSON object of environment variables for MCP servers'
        required: false

  workflow_dispatch:
    inputs:
      prompt:
        description: 'The prompt to execute with Copilot CLI'
        required: true
        type: string
      
      system_prompt:
        description: 'System prompt with guidelines that should be emphasized and followed'
        required: false
        type: string
        default: ''
      
      mcp_config:
        description: 'MCP server configuration as JSON string or file path (prefix with @)'
        required: false
        type: string
        default: ''
      
      copilot_model:
        description: 'AI model to use'
        required: false
        type: choice
        options:
          - claude-sonnet-4.5
          - claude-sonnet-4
          - gpt-5
        default: 'claude-sonnet-4.5'
      
      allow_all_tools:
        description: 'Allow all tools to run automatically'
        required: false
        type: boolean
        default: true
      
      allow_all_paths:
        description: 'Allow access to any path'
        required: false
        type: boolean
        default: false
      
      log_level:
        description: 'Log level'
        required: false
        type: choice
        options:
          - default
          - info
          - debug
          - error
          - warning
        default: 'info'

jobs:
  copilot-cli:
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout_minutes }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN || github.token }}
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
          cache: 'npm'
      
      - name: Install GitHub Copilot CLI
        run: |
          echo "Installing GitHub Copilot CLI..."
          npm install -g @github/copilot
          
          # Verify installation
          copilot --version
      
      - name: Setup MCP Environment Variables
        if: ${{ secrets.MCP_ENV_VARS != '' }}
        run: |
          echo "Setting up MCP environment variables..."
          echo '${{ secrets.MCP_ENV_VARS }}' | jq -r 'to_entries[] | "export \(.key)=\(.value)"' >> $GITHUB_ENV
      
      - name: Create MCP configuration file
        if: ${{ inputs.mcp_config != '' && !startsWith(inputs.mcp_config, '@') }}
        run: |
          echo "Creating MCP configuration file..."
          echo '${{ inputs.mcp_config }}' > /tmp/mcp-config.json
          echo "MCP_CONFIG_FILE=/tmp/mcp-config.json" >> $GITHUB_ENV
      
      - name: Validate MCP configuration file
        if: ${{ inputs.mcp_config != '' && startsWith(inputs.mcp_config, '@') }}
        run: |
          CONFIG_FILE="${{ inputs.mcp_config }}"
          CONFIG_FILE="${CONFIG_FILE#@}"  # Remove @ prefix
          if [ ! -f "$CONFIG_FILE" ]; then
            echo "Error: MCP configuration file '$CONFIG_FILE' not found"
            exit 1
          fi
          echo "MCP_CONFIG_FILE=$CONFIG_FILE" >> $GITHUB_ENV
      
      - name: Build Copilot CLI command
        id: build-command
        run: |
          echo "Building Copilot CLI command..."
          
          # Combine system prompt and user prompt
          FULL_PROMPT="${{ inputs.prompt }}"
          if [ -n "${{ inputs.system_prompt }}" ]; then
            FULL_PROMPT="IMPORTANT: Please follow these guidelines strictly: ${{ inputs.system_prompt }}

${{ inputs.prompt }}"
          fi
          
          # Start with base command using the full prompt
          CMD="copilot -p \"$FULL_PROMPT\""
          
          # Add model
          if [ -n "${{ inputs.copilot_model }}" ]; then
            CMD="$CMD --model ${{ inputs.copilot_model }}"
          fi
          
          # Add tool permissions
          if [ "${{ inputs.allow_all_tools }}" = "true" ]; then
            CMD="$CMD --allow-all-tools"
          fi
          
          if [ "${{ inputs.allow_all_paths }}" = "true" ]; then
            CMD="$CMD --allow-all-paths"
          fi
          
          # Add allowed tools
          if [ -n "${{ inputs.allowed_tools }}" ]; then
            IFS=',' read -ra TOOLS <<< "${{ inputs.allowed_tools }}"
            for tool in "${TOOLS[@]}"; do
              tool=$(echo "$tool" | xargs)  # Trim whitespace
              CMD="$CMD --allow-tool \"$tool\""
            done
          fi
          
          # Add denied tools
          if [ -n "${{ inputs.denied_tools }}" ]; then
            IFS=',' read -ra TOOLS <<< "${{ inputs.denied_tools }}"
            for tool in "${TOOLS[@]}"; do
              tool=$(echo "$tool" | xargs)  # Trim whitespace
              CMD="$CMD --deny-tool \"$tool\""
            done
          fi
          
          # Add additional directories
          if [ -n "${{ inputs.additional_directories }}" ]; then
            IFS=',' read -ra DIRS <<< "${{ inputs.additional_directories }}"
            for dir in "${DIRS[@]}"; do
              dir=$(echo "$dir" | xargs)  # Trim whitespace
              CMD="$CMD --add-dir \"$dir\""
            done
          fi
          
          # Add MCP configuration
          if [ -n "$MCP_CONFIG_FILE" ]; then
            CMD="$CMD --additional-mcp-config @$MCP_CONFIG_FILE"
          fi
          
          # Add MCP server options
          if [ "${{ inputs.disable_builtin_mcps }}" = "true" ]; then
            CMD="$CMD --disable-builtin-mcps"
          fi
          
          if [ "${{ inputs.enable_all_github_mcp_tools }}" = "true" ]; then
            CMD="$CMD --enable-all-github-mcp-tools"
          fi
          
          # Add disabled MCP servers
          if [ -n "${{ inputs.disable_mcp_servers }}" ]; then
            IFS=',' read -ra SERVERS <<< "${{ inputs.disable_mcp_servers }}"
            for server in "${SERVERS[@]}"; do
              server=$(echo "$server" | xargs)  # Trim whitespace
              CMD="$CMD --disable-mcp-server \"$server\""
            done
          fi
          
          # Add log level
          if [ -n "${{ inputs.log_level }}" ]; then
            CMD="$CMD --log-level ${{ inputs.log_level }}"
          fi
          
          # Add no-color for better CI output
          CMD="$CMD --no-color"
          
          echo "command=$CMD" >> $GITHUB_OUTPUT
          echo "Generated command: $CMD"
      
      - name: Authenticate with GitHub
        run: |
          echo "Setting up GitHub authentication..."
          if [ -n "${{ secrets.GITHUB_TOKEN }}" ]; then
            export GH_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          else
            export GH_TOKEN="${{ github.token }}"
          fi
          
          # Test authentication
          gh auth status || echo "Warning: GitHub CLI authentication may not be properly configured"
      
      - name: Execute Copilot CLI
        working-directory: ${{ inputs.working_directory }}
        timeout-minutes: ${{ inputs.timeout_minutes }}
        run: |
          echo "Executing Copilot CLI command..."
          echo "Working directory: $(pwd)"
          echo "Command: ${{ steps.build-command.outputs.command }}"
          
          # Set GitHub token for Copilot CLI
          if [ -n "${{ secrets.GITHUB_TOKEN }}" ]; then
            export GH_TOKEN="${{ secrets.GITHUB_TOKEN }}"
            export GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          else
            export GH_TOKEN="${{ github.token }}"
            export GITHUB_TOKEN="${{ github.token }}"
          fi
          
          # Execute the command
          eval "${{ steps.build-command.outputs.command }}"
      
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: copilot-cli-logs
          path: |
            ~/.copilot/logs/
            /tmp/mcp-config.json
          retention-days: 7
          if-no-files-found: ignore
      
      - name: Create summary
        if: always()
        run: |
          echo "## Copilot CLI Execution Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Prompt:** ${{ inputs.prompt }}" >> $GITHUB_STEP_SUMMARY
          if [ -n "${{ inputs.system_prompt }}" ]; then
            echo "**System Prompt:** ${{ inputs.system_prompt }}" >> $GITHUB_STEP_SUMMARY
          fi
          echo "**Model:** ${{ inputs.copilot_model }}" >> $GITHUB_STEP_SUMMARY
          echo "**Working Directory:** ${{ inputs.working_directory }}" >> $GITHUB_STEP_SUMMARY
          echo "**Status:** ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ -n "${{ inputs.mcp_config }}" ]; then
            echo "**MCP Configuration:** Enabled" >> $GITHUB_STEP_SUMMARY
          else
            echo "**MCP Configuration:** None" >> $GITHUB_STEP_SUMMARY
          fi
          
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Generated Command:**" >> $GITHUB_STEP_SUMMARY
          echo '```bash' >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.build-command.outputs.command }}" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY