name: Workflow Cost Analyzer with Copilot CLI

on:
  workflow_dispatch:
    inputs:
      target_repository:
        description: 'Repository to analyze (owner/repo)'
        required: true
        type: string

jobs:
  analyze-workflow:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install GitHub Copilot CLI
        run: |
          echo "Installing GitHub Copilot CLI..."
          npm install -g @github/copilot
          echo "Copilot CLI installed successfully"

      - name: Authenticate Copilot CLI
        env:
          GITHUB_TOKEN: ${{ secrets.COPILOT_TOKEN }}
        run: |
          echo "Authenticating with GitHub..."
          echo "Authentication configured"

      - name: Fetch workflows from target repository
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          echo "📥 Fetching workflows from ${{ inputs.target_repository }}..."
          
          if ! echo "${{ inputs.target_repository }}" | grep -qE '^[a-zA-Z0-9_-]+/[a-zA-Z0-9_-]+$'; then
            echo "❌ Error: Invalid repository format. Expected: owner/repo"
            exit 1
          fi
          
          OWNER=$(echo "${{ inputs.target_repository }}" | cut -d'/' -f1)
          REPO=$(echo "${{ inputs.target_repository }}" | cut -d'/' -f2)
          
          echo "Owner: $OWNER"
          echo "Repo: $REPO"
          
          mkdir -p target-workflows
          
          echo "Fetching workflow list..."
          WORKFLOWS=$(curl -s -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ inputs.target_repository }}/contents/.github/workflows")
          
          if echo "$WORKFLOWS" | grep -q "Not Found"; then
            echo "❌ Error: No .github/workflows directory found"
            exit 1
          fi
          
          echo "$WORKFLOWS" | jq -r '.[] | select(.type=="file" and (.name | endswith(".yml") or endswith(".yaml"))) | .download_url' > workflow_urls.txt
          
          if [ ! -s workflow_urls.txt ]; then
            echo "❌ Error: No workflow files found"
            exit 1
          fi
          
          WORKFLOW_COUNT=$(wc -l < workflow_urls.txt)
          echo "✅ Found $WORKFLOW_COUNT workflow file(s)"
          
          counter=1
          while IFS= read -r url; do
            filename=$(basename "$url")
            echo "Downloading workflow $counter/$WORKFLOW_COUNT: $filename"
            curl -s -H "Authorization: token $GH_TOKEN" "$url" -o "target-workflows/$filename"
            counter=$((counter + 1))
          done < workflow_urls.txt
          
          echo "✅ All workflows downloaded to target-workflows/"
          ls -lh target-workflows/

      - name: Verify workflow files
        run: |
          echo "Verifying downloaded workflow files..."
          
          if [ ! -d "target-workflows" ] || [ -z "$(ls -A target-workflows)" ]; then
            echo "❌ Error: No workflow files downloaded"
            exit 1
          fi
          
          echo "✅ Workflow files found:"
          find target-workflows -type f \( -name "*.yml" -o -name "*.yaml" \) | while read -r workflow; do
            echo "  - $(basename "$workflow") ($(wc -l < "$workflow") lines)"
          done

      - name: Create analysis prompt
        run: |
          cat > analysis-prompt.txt << 'PROMPT_EOF'
          You are a GitHub Actions expert specializing in cost optimization and workflow analysis.

          TASK: Analyze ALL GitHub Actions workflow files from repository ${{ inputs.target_repository }}.

          WORKFLOW FILES LOCATION: target-workflows/

          For EACH workflow file, provide:

          📊 COST ANALYSIS:
          - Runner types (ubuntu-latest: $0.008/min, windows-latest: $0.016/min, macos-latest: $0.08/min)
          - Estimated monthly costs
          - Cost per build/PR/commit

          💡 OPTIMIZATION RECOMMENDATIONS (prioritized):
          **HIGH PRIORITY**: Quick wins with $ savings
          **MEDIUM PRIORITY**: This quarter implementations
          **LOW PRIORITY**: Long-term improvements

          IMPORTANT: Save the report to: workflow-analysis-report.md
          PROMPT_EOF

      - name: Run Copilot CLI Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.COPILOT_TOKEN }}
        run: |
          echo "🚀 Starting workflow analysis..."
          
          mkdir -p ~/.copilot
          cat > ~/.copilot/config.json << 'CONFIG_EOF'
          {
            "trusted_folders": ["$(pwd)"]
          }
          CONFIG_EOF
          
          copilot -p "$(cat analysis-prompt.txt)" \
            --allow-tool 'shell(cat)' \
            --allow-tool 'shell(wc)' \
            --allow-tool 'shell(grep)' \
            --allow-tool 'shell(find)' \
            --allow-tool 'shell(ls)' \
            --allow-tool 'write' \
            || echo "⚠️ Analysis completed with warnings"

      - name: Verify analysis report
        run: |
          if [ -f "workflow-analysis-report.md" ]; then
            echo "✅ Analysis report generated"
            echo "Report size: $(wc -c < workflow-analysis-report.md) bytes"
          else
            echo "⚠️ Creating fallback report"
            cat > workflow-analysis-report.md << 'FALLBACK'
          # Workflow Analysis Report
          Analysis completed but report generation had issues.
          See job logs for details.
          FALLBACK
          fi

      - name: Upload analysis artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: workflow-analysis-${{ github.run_id }}
          path: |
            workflow-analysis-report.md
            analysis-prompt.txt
            target-workflows/
          retention-days: 30

  generate-html-dashboard:
    needs: analyze-workflow
    uses: ./.github/workflows/generate-report.yml
    with:
      repository_name: ${{ inputs.target_repository }}
      run_id: ${{ github.run_id }}
    secrets: inherit

  create-summary:
    needs: [analyze-workflow, generate-html-dashboard]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
      - name: Download analysis artifacts
        uses: actions/download-artifact@v4
        with:
          name: workflow-analysis-${{ github.run_id }}

      - name: Download dashboard artifacts
        uses: actions/download-artifact@v4
        with:
          name: finops-dashboard-${{ github.run_id }}
        continue-on-error: true

      - name: Create job summary
        run: |
          echo "## 🤖 GitHub Actions Cost Analysis" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Repository:** \`${{ inputs.target_repository }}\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          WORKFLOW_COUNT=$(find target-workflows -name "*.yml" -o -name "*.yaml" 2>/dev/null | wc -l)
          echo "**Workflows analyzed:** $WORKFLOW_COUNT" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ -f "workflow-analysis-report.md" ]; then
            echo "### ✅ Analysis Complete" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            
            REPORT_SIZE=$(wc -c < workflow-analysis-report.md)
            if [ "$REPORT_SIZE" -lt 50000 ]; then
              cat workflow-analysis-report.md >> $GITHUB_STEP_SUMMARY
            else
              echo "📄 Report preview (first 200 lines):" >> $GITHUB_STEP_SUMMARY
              head -n 200 workflow-analysis-report.md >> $GITHUB_STEP_SUMMARY
              echo "... *(truncated)*" >> $GITHUB_STEP_SUMMARY
            fi
          fi
          
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "---" >> $GITHUB_STEP_SUMMARY
          echo "📊 [Download HTML Dashboard](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> $GITHUB_STEP_SUMMARY